planner_agent_config:
  model_name: "gpt-4o"
  temperature: 0

execution_agent_config:
  model_name: "gpt-4o"
  temperature: 0
  max_tokens: 225

supervisor_agent_config:
  model_name: "gpt-4o"
  temperature: 0
  max_tokens: 225

general_conversation_agent_config:
  model_name: "gpt-3.5-turbo"
  temperature: 0
